spring.application.name=mini-project

spring.datasource.url=jdbc:postgresql://localhost:5432/db_parkify
spring.datasource.username=parkify
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
server.error.include-message=never

spring.jpa.defer-datasource-initialization=true

jwt.secret=${JWT_SECRET:TXlUZXN0U2VjcmV0S2V5VGhhdElzTG9uZ0Vub3VnaDEyMw==}
jwt.expiration=${JWT_EXPIRATION:PT10H}

spring.config.import=classpath:content-config.properties,optional:classpath:config.properties

