frontend.origin=http://localhost:5173

# ================================================
# Conexión a la BD remota de Supabase en perfil "dev"
# ================================================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate creará/actu­alizará el esquema automáticamente en dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# (Si quieres ver en consola las consultas SQL)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto en el que arrancará tu aplicación localmente
server.port=8080

