name: Build and Push Backend Image

on:
  push:
    branches:
      - devops
  workflow_dispatch:  # 👈 habilita correrlo manualmente

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: parkify-igrowker
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t southamerica-east1-docker.pkg.dev/parkify-igrowker-v1/backend-repo/backend:latest .

      - name: Push Docker image
        run: |
          docker push southamerica-east1-docker.pkg.dev/parkify-igrowker-v1/backend-repo/backend:latest

